### ISSUE TITLE
Beacon v1.0.0

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh/approval-tracker#1]
Beacon has submitted v1.0.0 for approval. Specification is available from https://github.com/ga4gh-beacon/specification/blob/release-1.0.0/beacon.md

**Comment by rishidev** [comment]
REWS specification has been filled in, reviewed with one recommendation, which has been acted upon. This comment acknowledges REWS Approval.

**Comment by juhtornr** [comment]
All the changes requested by the PRC are now done in the [specification](https://github.com/ga4gh-beacon/specification/blob/release-1.0.0/beacon.md).

**Comment by lairdm** [comment]
It all looks good, I approve. Thanks.

**Comment by juhtornr** [comment]
Yes, looks good to me so I approve.

**Comment by andrewyatz** [comment]
Approved from me too. That's PRC approved then

**Comment by rishidev** [comment]
@ckritzer will be performing the security review

**Comment by ckritzer** [comment]
Reviewed Spec, looks good - Approved.  Very organised documentation - well done, all.
