### ISSUE TITLE
Variant Representation

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#11]

**Comment by MKonopko** [comment]
Forms submitted to Secretariat, PRC, REWS and Security 24/6.

**Comment by JoaoAndreSa** [comment]
I just found one last mention of "reference" implementation [here](https://github.com/ga4gh/vr-python). Just remove it and it's ready to be approved by the DSWS :)

**Comment by larrybabb** [comment]
I think Alex will need to do a new build (zip and repackage). It's his call. I do not know the process. 

Alex - if you want to explain the procedure so I can be a backup going forward I'd be happy to learn and do that.

**Comment by ahwagner** [comment]
I think that @JoaoAndreSa is pointing to the vr-python GitHub description–the VR spec does not contain this text.

I'll leave it to @reece if he wants to remove the vr-python usage of "reference implementation".

**Comment by reece** [comment]
Seems not worth arguing about. I removed "reference".

For the record though, it's important to clarify that the PRC is for the spec and schema. The vr-python implementation is NOT part of the product (and therefore not part of the review).

**Comment by JoaoAndreSa** [comment]
@reece there is a link in the [documentation](https://vr-spec.readthedocs.io/en/1.0rc/implementations.html) for this repo so I thought it was part of the product. Sorry if it was not the case.

**Comment by larrybabb** [comment]
@reece do we need to state in the spec that the Implementations are not part of the spec? Should the readers of the spec have transparency on which portions of the spec were reviewed and approved by GA4GH and which were external to that review process?

**Comment by MKonopko** [comment]
@JoaoAndreSa In terms of the Security Review, we're good to go, then?  Would you give us the fancy "security approved" badge if so?

**Comment by JoaoAndreSa** [comment]
@larrybabb it is somewhat already there: _Security_ section of the [README](https://github.com/ga4gh/vr-python/blob/master/README.rst)

**Comment by JoaoAndreSa** [comment]
@MKonopko in terms of security it's good to go, but it seems I cannot edit the label (maybe I don't have permission to do this)

**Comment by MKonopko** [comment]
> @MKonopko in terms of security it's good to go, but it seems I cannot edit the label (maybe I don't have permission to do this)

I sent you an invite to be a collaborator.  I hope that resolves the issue?  If not, I will just use your written response here as official approval and change the label myself.  Thanks!

**Comment by JoaoAndreSa** [comment]
It solved the problem. Already added the label :) Thanks

**Comment by MKonopko** [comment]
Much appreciated!

**Comment by reece** [comment]
@JoaoAndreSa @larrybabb: You both raise a good point. I think we should clarify in the [Implementations section](https://vr-spec.readthedocs.io/en/1.0rc/implementations.html) are not supported by GA4GH.  See https://github.com/ga4gh/vr-spec/issues/158 for proposal.

**Comment by julesjacobsen** [comment]
The Variant Representation specification passed the approval of the Product Review Committee on August 19th 2019.

Reviewers:
@briandoconnor 
@melissacline
@julesjacobsen

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee 2019-09
