### ISSUE TITLE
Data Repository Service (DRS) v1

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#13]

**Comment by rishidev** [comment]
[Product submitted for approval](https://docs.google.com/document/d/12eWLO4AUy0mojwGHPnN_dTLfYM4J9y_iav6hH21qHVY/edit#).

**Comment by rishidev** [comment]
Approval Process not yet completed

**Comment by rishidev** [comment]
[PRC Comments for the Cloud Work Stream and responses](https://docs.google.com/document/d/1gCTFFomdUhP7dPJD6H-eqQ77OmLszvKGDqJXaBkU9SU/edit?usp=sharing)

**Comment by JoaoAndreSa** [comment]
A security review has been done and no action points were identified. The DSWS approves this API.

**Comment by f-marino** [comment]
Approved by Data Security

**Comment by mfiume** [comment]
I approve this spec

**Comment by pr80ik** [comment]
I approve this spec

**Comment by susheel** [comment]
I approve this specification

**Comment by dglazer** [comment]
Thank you @mfiume @pr80ik @susheel. 
@rishidev -- is the right tracking protocol to now replace the "Awaiting PRC" label with "PRC Approved"?

**Comment by rishidev** [comment]
Thanks all!

@dglazer yes, that has now been done, and we can close after the Steering Committee meeting in October.

**Comment by briandoconnor** [comment]
Thanks everyone!!!

**Comment by rishidev** [comment]
Approved at Steering Committee 2019-10-23
