### ISSUE TITLE
GA4GH Passports

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#14]

**Comment by MKonopko** [comment]
Forms submitted to Secretariat, PRC, Data Security, and REWS 24/6

**Comment by MKonopko** [comment]
PRC gave conditional approval waiting for the Google Implementation.  That has now been submitted and we're waiting for the final review.  Updated Security review has happened and some changes are being made.  Waiting on REWS updated assessment

**Comment by f-marino** [comment]
Data Security Approved

**Comment by MKonopko** [comment]
Received PRC approval:
8 Oct: Martin Kuba: "Yes from me "
9 Oct: David Glazer: "Yes from me too."
9 Oct: Dylan Spalding: "Yes from me"
10 Oct: Johan Ordish: "I’m okay with giving final approval."

**Comment by rishidev** [comment]
Approved at Steering Committee 2019-10-23
