### ISSUE TITLE
GA4GH AAI

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#15]

**Comment by MKonopko** [comment]
Forms submitted to Secretariat, PRC, REWS, and Security 24/6

**Comment by MKonopko** [comment]
Received PRC approval:
8 Oct: Martin Kuba: "Yes from me "
9 Oct: David Glazer: "Yes from me too."
9 Oct: Dylan Spalding: "Yes from me"
10 Oct: Johan Ordish: "I’m okay with giving final approval."

**Comment by f-marino** [comment]
Data Security Approved

**Comment by rishidev** [comment]
Approved at Steering Committee 2019-10-23
