### ISSUE TITLE
Beacon API v2

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#18]

**Comment by Neerjah** [comment]
PRC Meeting 1: December 20th @ 14:00 UTC
PRC Meeting 2: January 10th @ 12:00pm UTC

**Comment by Neerjah** [comment]
- Minutes and the recording from the first PRC meeting can be found [here](https://docs.google.com/document/d/1G9gtAhuljSfYRyHsvRQhpRIBEeRRz1NIS-dLZShz-KA/edit?usp=sharing). 
- Consolidated feedback from the first meeting can be found [here](https://docs.google.com/spreadsheets/d/1JjK4GsKkw9MBVr6OxN_9JdjcjWokF4o930qU67OydKA/edit?usp=sharing).
