### ISSUE TITLE
Task Execution Service (TES) API v1 

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#19]

**Comment by rishidev** [comment]
The TES API v1 has now been formally submitted for the GA4GH Approval Process. [Submission form here](https://docs.google.com/document/d/1NcW2kctNcaTjb_u8ZaXBE_DmPp6SeNjQu0PUSqiOmTA/edit#).

**Comment by f-marino** [comment]
Approved by Data Security

**Comment by uniqueg** [comment]
I approve this as a member of the PRC (DP representative)

**Comment by ohofmann** [comment]
I approve this as a member of the PRC

**Comment by juriste** [comment]
Approved by REWS.

As discussed, the following language should be included in documentation:

> A stand-alone security review has been performed on the API. Nevertheless, any implementation that is linked to from the documentation accompanying the API is done so without any security guarantees. If you integrate this code into your application it is AT YOUR OWN RISK AND RESPONSIBILITY to arrange for an audit to ensure compliance with any applicable regulatory and security requirements, especially where personal data may be at issue.

**Comment by jb-adams** [comment]
approved during the January 20th, 2021 Steering Committee meeting
