### ISSUE TITLE
refget v1.0.0

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#2]
Version 1.0.0 of the Reference Retrieval API

**Comment by raskoleinonen** [comment]
Approved subject to accepting pull request:

https://github.com/samtools/hts-specs/pull/336

**Comment by harindra-a** [comment]
looks OK to me! Lots of hard work from folks here. Good luck at steering committee vote!

**Comment by rishidev** [comment]
Semantic version number change to 1.0.0 also required

**Comment by kkmattil** [comment]
Document looks OK. I am looking forward to start using the implementations.

**Comment by ckritzer** [comment]
I've reviewed the refget team's responses to my inquiries and they all look good.  Thank you all for taking the time - these docs are well put together.  Approved.
