### ISSUE TITLE
Phenopackets v2.0

### ISSUE THREAD

**Issue by lindsmith** [ga4gh/approval-tracker#20]
Phenopackets submitted for approval on April 26, 2021.
- [Product Approval Form](https://docs.google.com/document/d/1dheKJHuNAWNa7CHOI81ujLx58cJ-2blc6FRjMhMmJgM/edit?usp=sharing)

Awaiting confirmation of availability from PRC members.

**Comment by Neerjah** [comment]
PRC Meeting 1: May 12, 2021
PRC Meeting 2: May 17, 2021
PRC Meeting 3: TBD

**Comment by lindsmith** [comment]
[PRC Meeting 2 Notes](https://docs.google.com/document/d/1GqTwj1II23BsY3SyRKsbB60FrcGL9CeES9fwkHikZOU/edit?usp=sharing)
[PRC Feedback Spreadsheet](https://docs.google.com/spreadsheets/d/19znq-oWgF3torVrjHe7PrY84LOxz_Vxj1Sbt3IrMvTc/edit?usp=sharing)

Meeting 3 is scheduled for Friday June 4, 2021.

**Comment by lindsmith** [comment]
After a PRC + Dev Team meeting ([notes here](https://docs.google.com/document/d/1GqTwj1II23BsY3SyRKsbB60FrcGL9CeES9fwkHikZOU/edit#heading=h.ktgl77oiffks)), the PRC has agreed to approve Phenopackets v2.0 with an addendum to generalize HTSfile. This means that Phenopackets will move forward to Steering Committee in two weeks, with the Phenopackets team working on HTSfile in the meantime. Jules will create a Github issue for everyone to comment/iterate on. As for the other issues raised on the spreadsheet, the PRC is comfortable with the responses and no further action is needed now.
