### ISSUE TITLE
BED v1

### ISSUE THREAD

**Issue by Neerjah** [ga4gh/approval-tracker#21]
BED submitted for approval on June 4, 2021.

[Product Approval Form](https://docs.google.com/document/d/1OxSDPqKBkVW3TDA1RNJSYAUWYAAwoo34yy4p74Zdflc/edit?usp=sharing)

**Comment by Neerjah** [comment]
**PRC Meeting 1:** June 24th at 1:00pm ET
**PRC Meeting 2:** July 6th at 2:30pm ET [RESCHEDULED! See below for new meeting time]
**PRC Meeting 2:** July 13th at 2:30pm ET

**Comment by michaelmhoffman** [comment]
Are there any comments from PRC meeting 1?

**Comment by Neerjah** [comment]
> Are there any comments from PRC meeting 1?

Yes. The comments have been collected and now we are just verifying that they successfully captured the outcomes of the discussion. We hope to have the PRC's comments back to the dev team by early next week.

**Comment by Neerjah** [comment]
[PRC Meeting 1 Notes](https://docs.google.com/document/d/1m6ZK_B4MxP3SJXNLz5mTlCEIURpoZRHGJGwBxgrxc34/edit?usp=sharing)
[PRC Feedback Tracker](https://docs.google.com/spreadsheets/d/1jPMdBi4e76Ppq9CzH8V3SAZcEFNnffnPZTbwvurWzcQ/edit?usp=sharing)

**Comment by Neerjah** [comment]
PRC comments from meeting 2 are currently being reviewed and verified by PRC members. An email to the dev team with next steps will follow.

**Comment by michaelmhoffman** [comment]
I have posted a revised version following public comments and Peer Review Commitee meeting 2 comments. This is discussed at samtools/hts-specs#570.

The following release artefacts are available:

- [BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210830/BEDv1.pdf)
- [latexdiff from revision 6063151](https://github.com/michaelmhoffman/hts-specs/releases/download/20210830/BEDv1-diff-from-6063151.pdf), the version GA4GH sent out for public comment
- [latexdiff from revision 1caa7c6](https://github.com/michaelmhoffman/hts-specs/releases/download/20210830/BEDv1-diff-from-1caa7c6.pdf), the previous release posted 2021-06-28

**Comment by michaelmhoffman** [comment]
Following one more public comment on samtools/hts-specs#570 I have made some additional revisions:

- [BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210831/BEDv1.pdf) revision 2a5cd5d
- [latexdiff from revision 6063151](https://github.com/michaelmhoffman/hts-specs/releases/download/20210831/BEDv1-diff-from-6063151.pdf), the version GA4GH sent out for public comment
- [latexdiff from revision af943fe](https://github.com/michaelmhoffman/hts-specs/releases/download/20210831/BEDv1-diff-from-af943fe.pdf), the previous release posted 2021-08-30

**Comment by michaelmhoffman** [comment]
I have addressed the remaining comments from this issue and the peer review committee.

- [BEDv1.pdf](https://github.com/michaelmhoffman/hts-specs/releases/download/20210923/BEDv1.pdf) revision 2481c79
- [latexdiff from revision 2a5cd5d](https://github.com/michaelmhoffman/hts-specs/releases/download/20210923/BEDv1-diff-from-2a5cd5d.pdf), the previous release posted 2021-08-31
