### ISSUE TITLE
Discovery Search API v1

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#3]
Repo for this is at https://github.com/ga4gh-discovery/ga4gh-discovery-search

**Comment by geoffjentry** [comment]
This looks good to me :+1:

**Comment by rishidev** [comment]
Nara Sobreira (PRC member) has approved this, registering on her behalf as she has no GitHub account.

**Comment by rnpandya** [comment]
+1 looks good to me

**Comment by ckritzer** [comment]
Re-write looks good!

**Comment by ckritzer** [comment]
I like the new Preface and the added Conventions and Terminology section.  Very crisp, clean, tidy.  Concept section is nicely filled out as well.  Good title change for Search and Results - nothing wrong with the old title (Request and Response) but this is much clearer.  Annnnnnd last but not least, yes the updates cover my question in Reserved Keys and Extensions.  Very nicely done, all.  Approved!

**Comment by rishidev** [comment]
Thank you very much to all the reviewers, this product is now ready to go to the Steering Committee meeting for Approval

**Comment by rishidev** [comment]
Rejected as is at Steering Committee in Basel 2018
