### ISSUE TITLE
Workflow Execution Service v1

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#4]
Repo at https://github.com/ga4gh/workflow-execution-service-schemas/

**Comment by ckritzer** [comment]
Updated WES API doc reviewed and Approved!  Nice work!

**Comment by ohofmann** [comment]
Okay from my side. Thanks for all the changes in response to the PRC requests!

**Comment by mfiume** [comment]
Reviewed and approved. This will go a long way for reproducible science. Thanks for your work on this.

**Comment by rishidev** [comment]
Comments from Aaron Kemp, 3rd PRC member.
There are a couple of comments in the document - in particular:
(1) repeating status codes and a question about richer errors
(2) the addition of a CANCELLING state 

Otherwise, LGTM

**Comment by rishidev** [comment]
Additional comment from Aaron Kemp, 3rd PRC member on Section 1.2 URI Descriptor on the document - we need to indicate that we are happy with a non-rooted base path.

**Comment by kemp-google** [comment]
LGTM subject to my comments that Rishi added above, sorry for the delay.
