### ISSUE TITLE
Data Use Ontology

### ISSUE THREAD

**Issue by MKonopko** [ga4gh/approval-tracker#5]

**Comment by rishidev** [comment]
[DUO Product Approval Submission Form available here](https://docs.google.com/document/d/1XAM8zGEDfNGkWwHLu2wLolPeket-Csv2eTcWnMi-Kx4/edit?ts=5c3c74fd#heading=h.gdow1korb9yh)

**Comment by rishidev** [comment]
Data Security Approval came on GA4GH Steering Committee call 2019-01-28

**Comment by MKonopko** [comment]
PRC Approvals:

24/1/19: Giselle Kerry
"I am happy to approve.

Thanks,
Giselle"

28/1/19: Marc Fiume
"I've reviewed and approved the changes. "

28/1/19: David Bernick
"I've reviewed and approved the changes."
