### ISSUE TITLE
rnaget API v1

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#6]
This API is being submitted for the approval process in March 2019.

Relevant documents (incomplete at the moment) are being worked on.

**Comment by rishidev** [comment]
Links to documents
- [Product Approval](https://docs.google.com/document/d/1-y6aKFb7dM6mLbUoqGPPfsNDK_18I3tiLK0WBun9QAM/edit#heading=h.gdow1korb9yh) (still in development)
- [Security Form](https://docs.google.com/document/d/1JNYCijnMhU96-CUSNjiWoE-5b4P5kLMa1wEkMNaBHR4/edit#heading=h.re5kk3dopqg1)
- [REWS Form](https://docs.google.com/document/d/1OQ_AcaD94Ukz_DeqFzzn4KoKWSe09pdfJvhgugYedTY/edit) (still in development)

**Comment by rishidev** [comment]
REWS [review has been completed and acted upon](https://github.com/ga4gh-rnaseq/schema/issues/32). They have linked to the document from the spec. 

@athorogood Please indicate REWS approval if ready to do so

**Comment by rishidev** [comment]
[Initial review from the PRC is now available](https://docs.google.com/document/d/1PmcIIZIBXzkRWP2u299z_BdTLUUBEuOkLjSJBJFvXdc/edit#).

**Comment by rishidev** [comment]
The initial PRC had returned with a status of 'Major Revisions Required'. To undertake the work specified in the PRC review the RNASeq team will be aiming to have this specification reviewed for the September Steering Committee meeting instead on the May one.

**Comment by rishidev** [comment]
This has been resubmitted. At this stage the PRC looks very comfortable with it, security was favourable, and REWS input is still to be received.

**Comment by JoaoAndreSa** [comment]
A security review has been done and no action points were identified. The DSWS approves this API.

**Comment by rishidev** [comment]
Approval Process not yet completed

**Comment by lauraclarke** [comment]
I approve the RNA API v1 specification

**Comment by andrewyatz** [comment]
I approve the v1 rnaget spec

**Comment by diekhans** [comment]
I approve the v1 rnaget spec

**Comment by rishidev** [comment]
Many thanks to the PRC members, this is now PRC Approved

**Comment by rishidev** [comment]
[PRC comments and RNASeq Team responses are captured here](https://drive.google.com/file/d/1SQXUPU1-kmI4eeqt2cuNQ4XzjIw1XxhB/view?usp=sharing)

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee 2019-09 (subject to some changes)

**Comment by rishidev** [comment]
Getting an additional review due to product changes.

**Comment by lindsmith** [comment]
[Notes from additional review are here.](https://docs.google.com/document/d/13yLv6l4cx7bR5PDbJtlcR8VHujgKdNbS9ckDROxJNDY/edit?usp=sharing)
Green = Positives
Yellow = Consider
Orange = Changes
Red = Must Change

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee Meeting 2020-01-22 UT
