### ISSUE TITLE
Crypt4GH File Format

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#7]

**Comment by rishidev** [comment]
[GA4GH Product Approval Form submitted ](https://docs.google.com/document/d/1GaLg8fdGuuOC2CtKjh_m-hgCNRRbOAkOHGrrxAkwpwU/edit?usp=sharing)

**Comment by rishidev** [comment]
Approval Process not yet completed

**Comment by rishidev** [comment]
[PRC notes are available here](https://docs.google.com/document/d/1hbS0moVRucrJ61J2F9fux7RZJgxeJgAec57dO4ne370/edit#heading=h.cam36uv6bmhy)

**Comment by jhubaux** [comment]
Approved by PRC: Chris, Cristina, JP

**Comment by f-marino** [comment]
Approved by Data Security

**Comment by rishidev** [comment]
Crypt4GH team [prepared a document detailing how they have responded to the request for changes from the first PRC meeting](https://docs.google.com/document/d/1PX-rdNhCGfEepAiCgRYKZBOhNG7rgYOAfogiUyBY_6c/edit#heading=h.5b6mkdn0m7mo). This also contains links to the updated documents as part of this process.

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee 2019-09
