### ISSUE TITLE
Service Info

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#8]

**Comment by juhtornr** [comment]
ELIXIR Beacon Network implementation conforms with service-info specification. More information can be found from:

https://gist.github.com/teemukataja/e2f81b12ad7f40dd453c263b534ee39d

**Comment by andrewyatz** [comment]
👍 from refget. We have a development branch that needs more work but this will be implemented

**Comment by f-marino** [comment]
Approved by Data Security

**Comment by rishidev** [comment]
This was approved via email by Adrian Thorogood to myself 2019-12-03 UT

**Comment by davidhansencsiro** [comment]
Approved
David Hansen, PRC member

**Comment by blankdots** [comment]
I approve this specification.
Stefan Negru, PRC member

**Comment by briandoconnor** [comment]
I see that my [concerns](https://docs.google.com/document/d/19B_TItlFaV_xdTSPqoImUNNQAAJk2pvbYgDvPeM8NG0/edit#heading=h.cam36uv6bmhy) from the PRC were [addressed](https://docs.google.com/document/d/144ONUsbCL39S_0vdtQ_a33N0EHcpBSVtGetNBzRYVzU/edit#).

I approve
Brian O'Connor

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee Meeting 2020-01-22 UT
