### ISSUE TITLE
Service Registry

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#9]

**Comment by f-marino** [comment]
Approved by Data Security

**Comment by davidhansencsiro** [comment]
Approved
David Hansen

**Comment by blankdots** [comment]
I approve this specification.
Stefan Negru, PRC member

**Comment by briandoconnor** [comment]
I see that my [concerns](https://docs.google.com/document/d/1KulOXEEuWz8EnomaeQJ2Nz6Ok-PaxsuapfLAX5152gE/edit#heading=h.cam36uv6bmhy) from the PRC were [addressed](https://docs.google.com/document/d/1gPo6fF8zcdYBx_yNH5xVi9mTYorDEqL0V6aNp655nrg/edit#).

I approve
Brian O'Connor

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee Meeting 2020-01-22 UT
